<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Use C# latest to enable new .NET features -->
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net8.0-windows10.0.19041;net462</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.30.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1150.38" />
  </ItemGroup>

  <!-- Conditionally obtain references for older targets -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="GoWebBrowser.cs" />
  </ItemGroup>

</Project>
