<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Use C# latest to enable new .NET features -->
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net8.0-windows7.0;net462</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\Radial.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Include="Northwoods.GoDiagram.WinForms" Version="10.1.2" />
  </ItemGroup>

</Project>
