<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\GuidedDragging.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Include="Northwoods.GoDiagram.Wpf" Version="11.0.0-a2" />
  </ItemGroup>

</Project>
