<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Use C# latest to enable new .NET features -->
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net8.0-windows10.0.19041;net462</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\SwimLane.projitems" Label="Shared" />

  <!-- Conditionally obtain references for older targets -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    
    <PackageReference Include="Northwoods.GoDiagram.WinForms" Version="11.0.0-a2" />
  </ItemGroup>

</Project>
