<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\Parallel.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Include="Northwoods.GoDiagram.Avalonia" Version="11.0.0-a2" />
    
  </ItemGroup>

</Project>
