<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Northwoods.GoDiagram.Avalonia" Version="11.0.0-a2" />
  </ItemGroup>

  <Import Project="..\DataInspector.projitems" Label="Shared" />

</Project>
